name: smart_museum
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  http: ^1.2.0

  redux_epics: ^0.15.1
  rxdart: ^0.27.7

  redux: ^5.0.0

  flutter_redux: ^0.10.0

  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0


  line_awesome_flutter: ^2.0.0

  image_picker: ^1.0.7

  intl: ^0.19.0

  google_fonts: ^6.1.0

  mobile_scanner: ^5.1.1
  pretty_qr_code: ^3.3.0

  audioplayers: ^6.0.0

  flutter_credit_card: ^4.0.1

  file_picker: ^8.0.5

  screenshot: ^2.5.0
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7

  freezed: ^2.4.6
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/entry page photo.jpg
    - assets/audio/01.mp3
    - assets/images/mastercard.png

